### ISSUE TITLE
Nice i like this plugin #Fix this

### ISSUE THREAD

**Issue by amlxp** [DaRealAqua/PrisonEssential#2]
Not work.. Have many problem in poggit

**Comment by iZeaoGamer** [comment]
Please send the error log. Stop stating it doesn't work without an actual error log.

**Comment by amlxp** [comment]
> Please send the error log. Stop stating it doesn't work without an actual error log.

Sorry dude, in repo This plugin Have 39 Problem. I see its not work:??

**Comment by amlxp** [comment]
> Please send the error log. Stop stating it doesn't work without an actual error log.


I wish repo plugin PrisonEssentials status OK :') and No Have Problem :')

**Comment by iZeaoGamer** [comment]
What do you mean it has 39 problems? If there’s an error log, then just post it so they can atleast do something about it. Also letting the developers know what those issues are so they can get it fixed. (If and when possible)

**Comment by DaRealAqua** [comment]
i have some problems with github not getting my files properly. I tried to fix it but I have to wait until github resolves.

**Comment by DaRealAqua** [comment]
This thing happened to me for the first time, it ruins the file but the file is intact.

**Comment by DaRealAqua** [comment]
And send please the error

**Comment by McMelonTV** [comment]
![prisonessentials](https://user-images.githubusercontent.com/62901799/78662904-85697380-78d1-11ea-9e94-d6f054f40633.jpg)
You mean this? It is okay and working, but Poggit is showing badly these things....

**Comment by McMelonTV** [comment]
_**Now, You can close this issue @amlxp / @DaRealAqua **_
