### ISSUE TITLE
Not a issue, but a question

### ISSUE THREAD

**Issue by JGYTVevo** [DaRealAqua/PrisonEssential#3]
Does this plugin support ScoreHud by JackMD? if not can you please add a addon for it please

**Comment by McMelonTV** [comment]
I would also like if there was addon for Scorehud but there is not any right now. You can try to make it yourself with this tutorial: https://github.com/JackMD/ScoreHud/wiki

**Comment by McMelonTV** [comment]
Ok I made the addon. :) You can try it and if it doesn't work, please tell me and I will look at it.
[You can download it here!](https://www.mediafire.com/file/yhm5fhnd2ltrnud/PrisonEssentialsAddon.php/file)

**Comment by JGYTVevo** [comment]
Thank you i will try

**Comment by JGYTVevo** [comment]
do i do the {rank] thing the same as rankup was setup?

**Comment by McMelonTV** [comment]
The codes are: {prisone_rank}, {prisone_prestige}, {prisone_rank_price}, {prisone_rank_next} and {prisone_prestige_next}

**Comment by JGYTVevo** [comment]
oh ok
thank you

**Comment by McMelonTV** [comment]
![prisonessentialsaddontest](https://user-images.githubusercontent.com/62901799/79855080-c3cf5a00-83ca-11ea-9f74-9f101dfa8e50.jpg)

**Comment by McMelonTV** [comment]
no problem :)

**Comment by McMelonTV** [comment]
Did you test it? I think that {prisone_rank_next} and {prisone_prestige_next} aren't working but i don't know why....

**Comment by JGYTVevo** [comment]
Just testing it now

**Comment by JGYTVevo** [comment]
when i added the addon and all the codes now the plugin wont load and just crash

**Comment by McMelonTV** [comment]
Can you send me the crashdump and scorehud.yml ?

**Comment by McMelonTV** [comment]
It works fine for me

**Comment by JGYTVevo** [comment]
ok will send to you

**Comment by JGYTVevo** [comment]
PocketMine-MP Crash Dump Wed Apr 22 03:58:56 UTC 2020

Error: Undefined index: jgytvevosalt
File: plugins/PrisonEssential_dev-7.phar/src/Prison/Main
Line: 103
Type: ErrorException

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PrisonEssentials v1.1

Code:
[94]     public function getNoPrestigeTag() : string{
[95]         return $this->getConfig()->get("no-prestige-tag");
[96]     }
[97] 
[98]     public function setRank(Player $player, string $rank) : void{
[99]         $this->players[$player->getLowerCaseName()]["rank"] = $rank;
[100]     }
[101] 
[102]     public function getRank(Player $player) : string{
[103]         return $this->players[$player->getLowerCaseName()]["rank"];
[104]     }
[105] 
[106]     public function rankExists(string $rank) : bool{
[107]         return isset($this->ranks[$rank]);
[108]     }
[109] 
[110]     public function getRanks() : array{
[111]         return $this->ranks;
[112]     }
[113] 

Backtrace:
#0 plugins/PrisonEssential_dev-7.phar/src/Prison/Main(103): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[29] Undefined index: jgytvevosalt, string[77] phar:///home/container/plugins/PrisonEssential_dev-7.phar/src/Prison/Main.php, integer 103, array[1])
#1 /home/container/plugin_data/ScoreHud/addons/PrisonEssentialsAddon(33): Prison\Main->getRank(object pocketmine\Player)
#2 plugins/ScoreHud.phar/src/JackMD/ScoreHud/ScoreHud(229): JackMD\ScoreHud\Addons\PrisonEssentialsAddon->getProcessedTags(object pocketmine\Player)
#3 plugins/ScoreHud.phar/src/JackMD/ScoreHud/ScoreHud(264): JackMD\ScoreHud\ScoreHud->process(object pocketmine\Player, string[27]  ..2..lName..f>..a..l{name})
#4 plugins/ScoreHud.phar/src/JackMD/ScoreHud/ScoreHud(208): JackMD\ScoreHud\ScoreHud->displayDefaultScoreboard(object pocketmine\Player)
#5 plugins/ScoreHud.phar/src/JackMD/ScoreHud/ScoreHud(171): JackMD\ScoreHud\ScoreHud->updateScore(object pocketmine\Player)
#6 plugins/ScoreHud.phar/src/JackMD/ScoreHud/task/ScoreUpdateTask(77): JackMD\ScoreHud\ScoreHud->addScore(object pocketmine\Player, string[18] ..l..4OP ..cPrison)
#7 src/pocketmine/scheduler/TaskHandler(134): JackMD\ScoreHud\task\ScoreUpdateTask->onRun(integer 61621)
#8 src/pocketmine/scheduler/TaskScheduler(176): pocketmine\scheduler\TaskHandler->run(integer 61621)
#9 src/pocketmine/plugin/PluginManager(643): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 61621)
#10 src/pocketmine/Server(2380): pocketmine\plugin\PluginManager->tickSchedulers(integer 61621)
#11 src/pocketmine/Server(2143): pocketmine\Server->tick()
#12 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
#13 src/pocketmine/Server(1584): pocketmine\Server->start()
#14 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
#15 src/pocketmine/PocketMine(296): pocketmine\server()
#16 (11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.12.0 [Protocol 390]
Git commit: 77d45bf11674a1360f58e32a14a3b09f423d860c
uname -a: Linux 03219a5c-7438-4129-807f-0b8dc888b22e 5.0.0-1034-gcp #35-Ubuntu SMP Tue Mar 17 03:56:45 UTC 2020 x86_64
PHP Version: 7.3.16
Zend version: 3.3.16
OS : Linux, linux

Loaded plugins:
BlazinFly 1.8.7 by iiFlamiinBlaze for API(s) 3.0.0
WorldProtect 2.3.8 by aliuly for API(s) 3.0.0
MonthlyCrates 1 by xvqle for API(s) 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
Gamemodes 1.0.0 by Fadhel for API(s) 3.0.0
CustomShopUI 4.0.5 by SaltyPixelDevz for API(s) 3.0.0
AutoClearLagg 3.0.1 by Twisted for API(s) 3.0.0
CellPE 2.0.3 by Bajan, Vaivez66 for API(s) 3.0.0
VanishV2 1.6 by superbobby for API(s) 3.0.0
MineReset 3.2.0 by Falk for API(s) 3.0.0
Slapper 1.5.2 by jojoe77777 for API(s) 3.9.0
BuycraftPM 2.0.1 by Tebex Limited for API(s) 3.0.0
Broadcaster 1.5 by EvolSoft for API(s) 3.0.0
BuilderTools 1.2.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
WorldGuard 1.1.1 by Chalapa for API(s) 3.0.0
MyPlot 1.6.14 by Wiez, Exxarion, jasonwynn10 for API(s) 3.4.0
ScoreHud 5.1.1 by JackMD for API(s) 3.0.0
PiggyCustomEnchants 2.1.5 by DaPigGuy for API(s) 3.11.2
AutoXP 1.1.0 by JackMD for API(s) 3.0.0
InvSee 1.0.0 by BlockHorizons for API(s) 3.0.0
CommandSpy 1.0.0 by tim03we for API(s) 3.0.0
NoFallDamage 1.0 by DeveloperNeb101 for API(s) 3.0.0
BankNotes 2.0.3 by AndreasHGK for API(s) 3.7.0
SeeDevice 0.0.7 by Palente for API(s) 3.0.0
AutoInv 0.0.10 by JackNoordhuis for API(s) 3.0.0
SellAll 1.3.0 by AndreasHGK for API(s) 3.0.0
PingTag 0.4 by UnknownBallin for API(s) 3.0.0
FormAPI 1.3.0 by jojoe77777 for API(s) 3.2.0
PurePerms 1.4.3 by 64FF00 & ProjectInfinity for API(s) 3.0.0
AdminTroll 1.2.0 by Swourire for API(s) 3.9.0
MultiWorld 1.5.2 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 3.0.0
PiggyCustomEnchantsShop 1.3.4 by DaPigGuy for API(s) 3.2.0
WarpUI 3.3.1 by XenialDan for API(s) 3.11.0
VanillaEnchantments 4.0.0 by TheAz928 for API(s) 3.0.0, 3.1.0
KitUI 1.3.6 by Infernus101 for API(s) 3.4.0
CustomAlerts 2.1 by EvolSoft for API(s) 3.0.0
Minion 1.0.4 by CLADevs for API(s) 3.0.0
MaxEnchants 1.2.0 by Xenophilicy for API(s) 3.0.0
RenameItems 1.1 by Wertzui123 for API(s) 3.0.0
TempRanks 0.6.9 by Heisenburger69 for API(s) 3.9.0
AutoRestarter 1.0.0 by  for API(s) 3.0.0
AuctionHouse 1.0.9 by Shock95x for API(s) 3.0.0
OnlineTime 1.3 by Zedstar16 for API(s) 3.0.0
TimeCommander 1.0.2 by TheDeibo for API(s) 3.0.2
PiggyCrates 2.0.5 by DaPigGuy for API(s) 3.2.0
Texter 3.4.6 by yuko_fuyutsuki, mfmfnek0, onebone, ogiwara, Shootsta_ERU0531, Toganon, ShadowArt, Marron0421, No4NaMe, SuperYYT, SuperAdam47 for API(s) 3.10.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
PrisonEssentials 1.1 by DaRealAqua for API(s) 3.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtXHtz27aW/yoYpbPX2RFlUZIlWx1nxrGdJnvjRBs7Te9WmQxEQhJikmAJUrLS6Xffcw7Ap+VH
XN2d/SNpZyyCxMHvvM8BH3+25ioJefplJRItVdQa99qtVIaiNXYPDkcHvdFRf9huBVyn50miktb4
z1a6ieF0i47PbzwRpzix3QqF1nyBpz5GvpjLSPhMwq+bMfu62KQrsVKaBylcOc+C4JUM8NJ4yZPx
/v7+UoVi31NRymFesh8H2UJGen+SSK2ic61FlEoefPHFyhl1cNK+Tjx7ev8CJsFgjKQt2e+eD3MD
WBr47vZBBAn34PfvrWdd9v209oDG8zGLlXct0hCoTqdZKgM9nX7EP+OxqMnuNY/8QCR7MkrFQiTs
sM10msho8Xvv6DO7V5jFlaPRZ7ZTWbZZDgcFwniS8M3v7ufnIKdnLtu+xhefp3z/0lOJeJ35+9z3
1e119QkO7/VRQubUdIqLOi8WIv3Ao+s9NfsqvLQmvknANyKhxXuFQvKFSh7+i3vXF2clgvzHXq93
BMuZ09NpPjydEhbQy1aMhGiSKA8MW/hXfKEfgNZ/ErThYCu0/JfzIjYQ7l68tBewAtbp9Dqd4B0P
Raczf9HpcDj6M4LDvwjk4Ekgu4cPgPSljgHMmZjzLEhpfKZ44j8gsoOnoHFH7gNoshhMUdDxAwCG
3wEg5fraHH0k+ldwvDcaPYAF3OABIIX+3MPPoL6g0xm8n8APz5gl4RwxRFTO3dfeUvgZxI19hJHH
ELe/3ZoQuj0usTsvVPQhi4rAM3SHPZdWO7x/tcv8CFQxbES64srptALMeZFsXeiouZDRxv6E/lzw
CDJKsjcc9O9fpQDkvAghllwtE8H914In6UzwdMu6bre58KVIIAnu9fqH3cZaBhIqq4LJeZFKr1xX
b1vDvWsN9xY/5owhumdm9+6Y7R4dde+ZbQOWSiyZ/l1kDg4Hd5DRKQjOTh80p0/o5wX83OuN7mLj
yxfIDWDUmZfmZv+Sa3EKhYR+q7iPNr/FHWyWxHTwVi0WVc8Yfr6VdMqwN/jM7sp6houD+7g4umXC
RkJm6pDtuRhuEvFHJsGL84Tr3plwS9rOxaSMJltXx1T7vPX5r3ZL7LC+2kURBJBsVpfRSgUrEcJ0
oOqDEDxcxZyFkWbyhHOe8gXycjSA8wz+xdkskB6bZ5GH7DDIrO/UJBE6lQuIRYu952xs1fknzD86
sPPwXyLSLInYT+lSasrJpyqaS5hCB3vTVqSc2JJyUr6Ytp7/jDSGlsZfeDCCA/x7eAcgbYsPE5HZ
T3EtMrOfEjiJGFdK+oTwqILQQjNz9O92MsF7q9YiOQXbx4S89/zz79MWkpq2PrNjQxWxut1uBazb
dQ1at9u7W35b4NaFCEq8U4rfB9VAHNQgHuQQh3dAxLnnN1Kneq8pxJlSgUE4uo1QgiGlexYnzgCU
+OfzcwPjsAbjyMJwu/dLSpOFURlLK7vunbKhNWktt1ddy0Vxtv760R386A5+dAc/uoMf3cGP7uBH
d/CjO/j3dwft1kLAVB5gSY2xGovuKhmAMgMBlru4rX7H7XW6OJ7JwIeCfnTUb7ekxrzeGs8hiQmo
4BOVKk8B2f5RFxaRWN+PRv7gYDZ33eFowN3+sDs/OBT9HncHvD/rHs0Hvb5/OOx6QDvh14GcwZxu
vlpm0b2VUXbDuv2ee8QPPGc06B86A7d35Bx2R3OnOzv0vcPDw1mvJ9hBp9vpOlBGDJyFF7Nn/QPn
4yyL0oxdXkzYVSbYBYcyYwTUxgfD8eCAfbw6Zb1ur8tuDodfhgNsRZYxIu8A10M4/CYin2Rgj+H0
F6VzWDBABwEdFG2ORuG+DPg3Gb0KNhVJl2PtVilgt3PYGcEIz9KlSjRWg1K+CngoZYQzBKqNxxJP
9JFFPBYRnwUCsIHtg/x9EQNSnAvntJqnZ9UBDFWwUJ3qdFrAqfzEvg38Bs3i/eXVp/cf3p7B0FrM
tEyFLVo/qSTwwf1T7N5K7mrDVQZ7IL3DOoM8kBkstiPGDLXpdI0IYoPAeHfJzuXVyYerj5MaM8s0
jTU4FpjrMpt1PBXuX4DvzaUI/IobObmPp4kQ+yHXKThfjVsQygW45TLYnCaQ83RFKvXxmt7rIrlZ
/RHsTNXXwMI1hI/plBaeTk0wfIx2zyHAqHBzMnlT4aIyWGXhoDPq9OpsqAjqsWhnjFhy06kwCIDm
dFpD8yBDvwALofJrWinH6p7YpdhTYecV95ci2BU3htp0WizftNLtXGxUlmYzQQbq7Rsiry6Rt9NM
pyq8XKr4Y1VdteEqhwNAf1Dn8BLau81E3ojgTKy+fRenVbO4h+v6CmCSFXSrHiRz+PWQCNBVwVOx
F93ESKqz4CiAkyxVpwEUYG/5YlGRQH28KgJkq+F6V2sJPu3vSsupITedwhLKQxABgIAmsIHpQYYb
scnCPNGbIAsvTvfr9NAaRBBMzqt2YAbqwbjb6dfZf8m/crTBX7lciW/D4a7kQHRB3QQi//sYj/2V
R1Ivf+1VOCmG6v46rHOis1gkMzWb7Sy1lBSn0xxD+esxzGBh9UFoUU2V5VjdMnu3w09wvStWoFS7
lsk1xBxMagkuD+GnguRBVi4DHoM4KozkI3WtHDSTwlf1VYkR/qsxc/Q39GIWflz83OJLJaL9nAdg
8GW28RI+TycX1aqtHGw6UjOOiJm4YW9lKHcYTfLloS8sCnUo2HJQZuv8Ecp7mcAVHhUvVeYqow0l
1nk7X6ngEiDujK1yYeCmhuIRFdt6ve4IQITUO+m10R20JyK5UjBa015luM4haNCZiZQ3jPX0m/CW
kwvIVTjhV3kjr0//Z1dse0g8DqF3Aj+cGWwpYkOV1pB+r0VXYO/XSOUV+y8ZT/xmvW4G63Jxm3Z9
uuTgI3xXMrDk3P50WmKo/n4K9zlNCrmbSaBq8dYMNHJHxx3U+fwkxTcYOb+54Ym5U/aVaxWtN1Hk
dmvcD76X+3oFbT0ZCltsuMrtYEqPZ+e/Srs8ieQy3QTkF+dcb05VGPLIx9Q/lwEVplaqhkcIiDmv
97gRBXO7Z1eN5vlQvca/ZQ9m229X5nD3nuZjwtpELhYbU1GeR96SR2nV+7edrQfxW4HujMOkX7J6
BeFCtHgqfzlBCOC30WwdfIL954vsbyG3nxfKv00aFfJvk1uu3/2/ULVZ+8nJ2+6XWw6AuTfR6lKI
CnN24IHm7mUAfvhaJfKbivTOEluV6HRqkHxPA25d/DKubh1VBh9gKpVht7/eWQNuyUH5XiB4nN6Q
lXcKCtjgjIf0tEHBTG24wU7DGcVKBAqqs3dihveyd8RUg+x0WkX0ePZe8uj6narv95RjD3RdJ5Gf
CK5f//LPGlej3fTcJXUoLHJIlZ+PKveFAEFJr6q6cqzKHqiiuYU54QEktZ2ZYbEu7v2XEL43cuSo
bEAE52xERBxpcuZuiYnvlEr8ZSZ3Fja+AtEoJ2q2DmS0MqHSgHqEvoLgJAhq2jIjdR/rN73sDlPs
7t4ULaDix+MyfLS44otaVjcjdUU1irmPEchzHb0EvwYYO9JSjSjmbgJS/HgMO69UEtY3V/ORB7R0
RxPd+xs2V1CcTi2I4sejNJMlYiKSsFZxFWN1dgbN+DccvHrV7bL/YJNE4Q26N9FcRjLd2c7NF7MA
6CZHVPn5lNCBc/NHXAo6GEj8UEZXiap5XmXwVtPZ2H9dqyyRidjVzkhODx86yTE8PqVdZEEqqe2o
tk/l4AMbPdt7Z3xPY5OlOruW8PuaB1Je639LRx0iUroNBCxXUf+dbrpCaHvDQRvY9zYddou77t+D
RzQeD3n31g7n3u7zkY0JIr7zxI4bFCRJTconntRvZNiB+i5pv9mP/iYi6J7PeNTs2Z5sVDdE0cft
awPhewp43B0OAm65w4dddWMnu3m2eYumESKuluLk21Hv8JbLtJHNp3O5MlCwtk+eUk3luPa38QSC
+KdMa9o0x003aOzhQx4QSZTpZrk/eDqfFZLTKYF4fEA0lnoSiKSmxdpwY0fh37txWl05v5dW4Hja
1ukFJF4EX70/YTag6p1mI2Cdvj2hQL8rxgw5uich86c1H5Wz+M2WrZ/q6AMpGOKHipcykN7Oqo8K
SWTkptzvqeN6kLkPAvl5k4palVUdbezgNLY0wTC+ZdLt9XfFWUlxOq3AePJmTklvv8oVsH4lwpge
uK4wXo7Vi/9h56jO+GshtYhmWbIQyfDou4qrSg17jxzqC0ynBbLHGy72dh8EPQVXuylTH79/v2dH
Wg3x1rJpO5N8ZdN8VoE8giN6VP61yrSoMVQZbvLTUBwUA9710cHN37PX7RWPtrSRUUK0RETIZw3f
g2y+j/Dllit6u7lgsjLYSHF1Bv9H+ChRd2f32QuC02mJ4cn+WFDbrzCE3gh/7R5gzVjr403l9m5V
MmdCzlSD9SfvrdcWf8wjX2UF33xQqzra3Lo72EGlfttE7yjd76jOCVnt4O9X4URm38Tam3oMsgP1
ynvQLNY22bX6Um3uwnk4j8Q1xqj8STD4tZBrnnD4Bc6tUjCvL+cfPnYP+pisrtSCR1RsXC65r9Yn
Cd68uuBJoqLuoIeXvFODd/wCKV3i4xj/+tdV/vPE5+Ggvh/ifn+syLc8Krve6nqjptM4DGOM7DcU
DZ9YJRfi2bcytTsnp0ueNjZOaKi5b+K62zZOvm+n7p6M1nrFKfjpSaJgod/ESkIYnJw7+Xjrjj0V
BFv+2sGOCpFB4TTfAqwI6fYLgvcUP2f8g+DByR8Zf6q02rVHdR6331l92ejhZIJPDYNvhAIsgxbv
bHmuG+Y4TqSctfxmbo87ji81wnd4pCWhoWfJO3GCtzVSiaGt9WxSHDHzpiPDFzqnyTR6ho9Dn8QJ
67msOxy7R2O3XzwOjReEKvWPa0iYeegeT5rFnFgl6bF7NOjSjPUSeHICKCSO6ZhHkcoiDx+fpRcD
ubeUwrz8qY9BQEgn5uvIsU/sghLNxJDf2Dn62IDhQaDWzjyQi2V6rObzci40niHYQY1eqGb5wMI+
aGkIz1UCcIoxSwjk6+MN5/w4XsV2ti/nc+llQbo5dokaPTsPFZID9pDKaKGPcTjAu0kOWuix2Xoq
xrQQfuUSfB/3+Oz81cnHt1c4aizQ+SMTyeYYrbAymICt5YjwdyfmWgN5//g/6R8IBYozR/OVsGhX
UqzRLFIOQj8+xKGbmbpx0CFy+Ri9yfgY72vAfzhIy3fqugx4tMj4QhyLaIHH+Oh78Tx0ZxMGaF0M
LZx5ZFgZyAXfkUT7YiBnVjMdsDcGqV8LlguO8USwdCkYZAgNP3jKPDSYlM0Ek5EXZD69ichu2TXS
ulQhzJwjgSZNzeeizRScSTSSZLNE8Gu2UVliaTE5Z6B/OZe0AqgeX0MONkj4nVgX5PZ9846ZZmsV
/SNl+JQYTxiKPQRmPTDKDSLEVz0N3+uliFgWLxLuA4HONEKJG2LjacTYs09LgcBYqmCVyGdAwr5b
AjJIwJUDSMi+OU1QAwXLAKvwS6QkL59ufbElve6EIyFSNpada23M6LUMPKGXWQpJFZzCvPM9ZtOW
8WPmBUoLf9oiZCfoYQydF1+vtQ+8s5Xk7L/RPPAaspP8WfgxI3vFqZDT14yjHWgFkOxCRhjckmJQ
WGvAHoOoiUWIoXAlRGpfI5HyjLPC5y21qCxwTh6RUwLGGborA5MAqSPc2YZZXeH11oGK0xVpPPsk
QeIqAsVx32fQ6Rj9IlR8pwkgcQ3BH2MUA63OBEoFpC8ghwSol4VcwbUrHkD43LOLQsx8jtTNiuC6
Ap3JAb3iq0VjOE1rv8vCGYgdzPZEbyIPXycDy0quwVA7dMFHUAf5Ts4pXraEMgjyMcMX63SbUYBh
NhCBw7VBFiG+so45kGQDyQXHwiwCE8VLDPFLsh/gCcw4UTcQNVMBYgCWyDWiAhzK1gJ6M0dnwGvQ
6NtMpv8A8aUJTfMFBm2yycZktgc8gMJZj8RCbDiW0zGRajoDxXeWZFGE6vTN3XlSAj0ipzvsTKzs
bxZiFmBewvWyXfVua5kokSTJ4tSMGoGhYELAZvki5YLBgZjADY3HcXwfH2BvR4A2gjanQNBgXZ2K
oeH7zeaiwtIgh0GKSTbG638J1AysB+sFZsbB0UKZYvAIxYLPNlCFd9ilEXWXhGuyO02/Qq2tJUme
LIphMjSEciPTxOFcAkQIeYA+IlrzRIh8SWPkoK2M3HOhQFEK4wBaBS60IJgOQRuzLnIBq1OMT+k9
x//3HGABdh9+zPR/Dz/0ajFBsPG5gGTJaQbhAzM1BNYcEK6ao3K7vYEFRkHgE3mFxaf/sQOE5BcE
CSMG8zLIbhFkNyZuhJdRdFcGsvFIzIbF1eLGg4pFlxyZwPX+6nzMrl6/uWRv31y8uYLgPXn75vyS
Tc4/MKhp/3n+oc3gInb1Hq46Z59ev397ziYf3p+eX152miGgJo/ewdCKA+ptqSjjYyDWyKC3FBSS
SRpFsHVB9pBrfIotdImDbawJs0QKSl3gEwI0WBPye5exGSODshUzbISX2cWIsiECobcM5CYj0Rrv
MYdgIUETOrevRluwHQaoLRYe1htGsgjX6NXMLXgA8xKxLlntdy2v+vl2SJbzvuV8wZMZeIbjqSAw
BTUFoO3SJVdDOHYWs7Mgdoc8yqi6qSKByi8DG3zeznNC0whzMzTpdT4HWobfsHTBDntvYr4xeChP
VBb4BRYJSWQdsRK/NoRjgg+MDrtdyyus9oqCxa0kSaZjKBS8zRMV5snWzLZXOFXTrGoYubGavGUb
bItJ1azjMq9IUWV4Ax7N0Bqyn4WxKd9MjcjsCQdP5Po6w4vsBMJOMHMO4AjSPDg73yJgSNqQ+GCF
lcAPoGQCA0O6BK0t8nIWgxauVqJq54o0NYKtWjsGDV56p5ywWfOWWXStc+ynPMZRGWYh5FjcmGN5
V4KKZKa1MyhKuaK/WFGSx9y2MajmY4uIFnSwzM4g6Q4KjZ0pc6pp01gbYdQz9M3FuQsZWvbCKmdU
OTgetK2i4O0MoFCtAuUjSg/QmQLDUIk5Nj3MzDEcltzBNCtP27rblfHistpFAeI7XTnd+0ndZ4fT
KBIpKmxsUwSUZksVmBJzxlNox7HUJ8gaP8PCbJKh2GZaK3vWpJaZKIpNk96eVbWUn8KwmmxSJN5m
jltRICmPFnbSHIxNARS1yzqW2mUsIX3DOTZLVOjjZBi0sDrsNdSCYEvHVNyx08nHNswFDDPwr7X0
weypVjDRs6DvEP0xG+Vld1mRa5JO5doOO/EhUC15MN+HXtW0Cb4AG7ZLwaIM93jQwCqOWKa9CrFq
K3J+g1ENS0wetE3QxKU/yQj6NWANoo+gWIaV9MdJNMnr8LL5xDYDJ63x/QmgmcVR7NjjRuNzYR1S
y2+iUDVW7LmGcUctr6agojeWU8m6g6OemfS8wyZ2TsDx5hd277YLtmZCK84TvkDuQF3Alo4DKmaw
tQ0BPMYBnqAKTwOJO0LUq+O3D4RO2cXVR0KqgSVke5alDPcGSMvlcqbv6ORhKEwzB2eNCS06gC9m
2WKc9zIvmIs9jK3ksGul83nHqk0zL/JOFqdZQ3GRmIlbhtrpUkGPisaZtzAib1IpuOEHipjmqzyI
4jZNvg+G50p/55DTIRIInuYxBpCaryrkJTO1W2BCVK7oGCo0Kl8i5QUyZjQX5HjBNyBDNJZQrfIO
FsO/jZlmDy0/Z5bUZbTIN6yq2xVXtN9gDMB83dfs1NC1VtuZtq2+B1afmrhg5zhmzpjFUFCsZIDL
mJhn/dmugkGbR4uiqI5wWtDMHe38qto+19YtItPlnYQqQ5uem+BsTRxFafYWKRmhO1PvDorB35RN
YPIHyi2VycR4JEyvOBOG2EzM0SJp25HSwTK3AFI67UbWspRhHxcq2AfPZLwJNc6/BsUEJIBtKLvb
YfIEKPm070KGCGDzyfi3QNMn68ZO2jHfMNKVaEHvLNNCtJ1b2Yp5c0aLzfAdB00uifIUCWoaP9Pm
Q6liuWN25yHPdjSnxjrQc1iPPWML6Fl0KZ5yd6OQUOe2iKyzrrmkpgYCB1T8RjexirMgN0Z7gGGf
rrEh4hDXo2LYia1XY3BFRx2zvMykLVaznTO2CQ93n6jFMsMmX1h14QcXin0BvxQbmruDHzJsDBXe
Vh+Ol1CZzVVFIeBkjrmBUly5VKgYgtLB21QdqQhxpKJNiC0C+EeK23meLqFj32PPs/I8sUARiy8W
CTSbZmOp2LnDQgo/VHfd5I/wgQO/P3uP361xbAw0qQBjwlqYOpSD56xpRU3ASwZorFPZW4bMU0je
WKZRzi2hgj7NeWtLkPQix4buajlF46oqOqhQIzSTyi5PG8JjvORthu+DUr5Ki4oFIu9cQBcNKoQA
FGE+MGfzvGL2jHht18jelarkmwyqM0htFMTyWGEJkubN+XyNW5o2vFZVnUILXYRqm5CQKF6f1w2o
WYyXuCBth9lJ+dZnp1zAnqmukEvz/pRno7bRrvGKyi5Dvi2cytTKM99PWNpBChjYENga0wYM3J6F
Mt6nIkvOC0JQqQMjZrMfA1DeZJsQB/RshMwTGw8k17aCh6KLh3GQH2ENABitrsa50sw5sFvc7Rmz
3yl5Q/ps0/bPZyRKxXmZJas3IYgNLKQS6dsGO79tRJ3ztoRF+ZwStKZakhozfOoYsNpsW4Vv1iUM
5ifDG02YFEzyKlccs1dvT67GvZ9H7YOjG7fdv+m3ez+7P/vCUybE7uFHbTyMrceHXROJzdHg4Lmp
esx+f7WvNR6OqQVkbLedqPKgfSPQmrdh5qNcWZLH5LyYT4qNfIo4QAcylUd3YnQuMCe/ywC2YMq7
Z68o1NBSdH2NSEaFQuXbkHbEoVqrU+6QKfoOJhP0LVHbB3nXWC5rqvlBIjMJherGtMx0HfILUKBK
N1nE+IzhkuhDLZIUsbrVbuFN/kjTnfPxny16aKDyRSn04upxIGc3dDutGAGjiLSuDcVenYj+A0CK
fu1LVeb7WcXxzIPSa1kdwTtJkc+T2liyiVNFT9CZp6o9+83g8oosqUGBDI8PxXS7fdft4aNbX7W9
+T6iJ9PmMqAHScoZ87T2Sa2FXzsKayeXkM5qjEKR59Nr6+XY5eRtTYDoHr75dph5+DacmXtq1avC
DciMvuVlf9HXwtwe7t4zqEK67kF30B3Bz5/egCeNPA/+PxqK4ehgPvRHPXHgzbvz3nA0HxwKdzjy
enw26/XZT6SdKK3JaHL2vqY9X32hVZuDRo21mcu6fsrE+IXKHvpwnflMGkk7Vlre1CbYnTX7OREX
P9LWbiUC1IgmuTDfACjmfxBzuz9Sk/oyVDW1XEoMO79d1ASvCZuuGYe2D9iiYcjFTEY82ZhvyNGT
YKm6FhGUXzUeG+YPh8jBrWvWiWwY1obTzJ59MvmbjM1DIAd0SBKX5fV//fW/QALI8w==
===END CRASH DUMP===

**Comment by JGYTVevo** [comment]
i couldnt download it due to my server hosting

**Comment by McMelonTV** [comment]
ok

**Comment by McMelonTV** [comment]
hmmmm there is something wrong when you dont have prestige.......

**Comment by JGYTVevo** [comment]
?

**Comment by McMelonTV** [comment]
can you also send me your scorehud.yml ?

**Comment by JGYTVevo** [comment]
oh yeah

**Comment by JGYTVevo** [comment]
---
# DO NOT EDIT THIS VALUE.
# ONLY FOR INTERNAL USE.
scorehud-version: 1

# Changing titles of the scoreboard.
# Can be of any number.
server-names:
- "§l§5Diamond §dNetwork"
- "§l§4OP §cPrison"


# Note: You can find links to the required/supported plugins via the README.md.
# IMPORTANT NOTE: You can only set a maximum of 15 lines and no more.
#
# You can edit the lines already set below and adjust them according to your needs.
#
# If you want same scoreboard to be displayed in every world then set per-world-scoreboard to false in config.yml.
#
# If you have per-world-scoreboard enabled and want to display a default scoreboard for a world you didn't mention
# in scoreboards key below then set use-default-score-lines to true in config.yml.
#
# After that edit the following score-lines to edit the scoreboard.
#
# You need to add addons for adding support for tags.
# If you want support for a plugin please ask the plugin author of that plugin to add support for ScoreHud by making an addon.
#
# For a list of addons go here https://github.com/JackMD/ScoreHud/blob/master/README.md#addons.
score-lines:
- " §2§lName§f>§a§l{name}"
- " §3§lMoney§f>§b§l{money}"
- " §4§lRank§f>§c§l{prisone_rank}"
- " §1§lNext rank price§f>§9§l{prisone_rank_price}"
- " §e§lPrestige§f>§6§l{prisone_prestige}"
- " §8§lPing§f>§7§l{ping}"

# If you want to display different scoreboards for every world then set per-world-scoreboard to true in config.yml.
# After that edit the following to suit your needs.
scoreboards:
# EXAMPLE CONFIGURATION:
# -------------------
# "world name":     | The name of the world. Enclose it in inverted commas.
#   lines:          | This key is important. And the plugin won't function without it.
#   - " Line #1"    | Line number one. You can use any of the above tags.
#   - " Line #2"    | You can add a maximum of 15 lines.
#--------------------
  "world":
    lines:
    - " §dName: §5{name}"
    - " §bOnline: §a{online} §c/ §d{max_online}"
  "world 2":
    lines:
    - " §dTPS: §5{tps}"
    - " §bLoad: §a{load}"
...

**Comment by McMelonTV** [comment]
IDK it should work..... try removing the prestige from your scorehud and tell me if it works

**Comment by JGYTVevo** [comment]
ok

**Comment by JGYTVevo** [comment]
still crashes

**Comment by McMelonTV** [comment]
hmmm then idk
i will have a look at it but not right now, sorry
maybe like in 2 hours

**Comment by JGYTVevo** [comment]
ok

**Comment by JGYTVevo** [comment]
ill see if its scorehud

**Comment by JGYTVevo** [comment]
its scorehud's issue

**Comment by JGYTVevo** [comment]
but i still think its this plugin aswell

**Comment by JGYTVevo** [comment]
JackMd said its the addon

**Comment by McMelonTV** [comment]
?

**Comment by JGYTVevo** [comment]
You need to fix the addon of scorehud

**Comment by JGYTVevo** [comment]
soemthing's wrong with it

**Comment by JGYTVevo** [comment]
Its the addon that you guys made for scorehud

**Comment by McMelonTV** [comment]
ok

**Comment by McMelonTV** [comment]
but it works fine for me so idk how xD

**Comment by McMelonTV** [comment]
and please make an issue here https://github.com/McMelonTV/PrisonEssentialsScorehudAddon/issues/new

**Comment by McMelonTV** [comment]
cuz this is repo for the pluin and not for scorehud addon
this scorehud addon is made by me and not by DaRealAqua
